class GameConstants:
    ROUND_COUNT = 100

    PLAYER_INITIAL_RESOURCES = 0
    AGENT_CONSUMPTION_RATE = 0
    AGENT_COLLECTION_RATE = 0

    GROW_RATE = 0
    GROW_THRESHOLD = 20
    FIELD_INITIAL_RESOURCES = 1
    FIELD_MAX_INITIAL_RESOURCES = 1
    FIELD_MAX_RESOURCES = 1

    BOMB_COUNTDOWN = 4
    SCORE_FOR_KILLING_ENEMY = 10
